name: parking_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_map: ^6.1.0
  flutter_paypal_payment: ^1.0.6
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  go_router: ^13.2.2
  latlong2: ^0.9.0
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null
